<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $customers = [
            [
                'name' => 'Budi Santoso',
                'email' => 'budi.santoso@email.com',
                'nik' => '3201012345678901',
                'phone' => '081234567890',
                'gender' => 'male',
                'birth_date' => '1990-05-15',
                'address' => 'Jl. Sudirman No. 123',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '10220',
                'identity_type' => 'ktp',
                'identity_number' => '3201012345678901',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Siti Nurhaliza',
                'email' => 'siti.nurhaliza@email.com',
                'nik' => '3201023456789012',
                'phone' => '081234567891',
                'gender' => 'female',
                'birth_date' => '1992-08-20',
                'address' => 'Jl. Gatot Subroto No. 45',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40111',
                'identity_type' => 'ktp',
                'identity_number' => '3201023456789012',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Ahmad Dahlan',
                'email' => 'ahmad.dahlan@email.com',
                'nik' => '3301014567890123',
                'phone' => '081234567892',
                'gender' => 'male',
                'birth_date' => '1985-03-10',
                'address' => 'Jl. Ahmad Yani No. 78',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'postal_code' => '50131',
                'identity_type' => 'ktp',
                'identity_number' => '3301014567890123',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Dewi Lestari',
                'email' => 'dewi.lestari@email.com',
                'nik' => '3501015678901234',
                'phone' => '081234567893',
                'gender' => 'female',
                'birth_date' => '1995-11-25',
                'address' => 'Jl. Diponegoro No. 12',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60271',
                'identity_type' => 'ktp',
                'identity_number' => '3501015678901234',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Rudi Hermawan',
                'email' => 'rudi.hermawan@email.com',
                'nik' => '5101016789012345',
                'phone' => '081234567894',
                'gender' => 'male',
                'birth_date' => '1988-07-08',
                'address' => 'Jl. Teuku Umar No. 56',
                'city' => 'Denpasar',
                'province' => 'Bali',
                'postal_code' => '80117',
                'identity_type' => 'ktp',
                'identity_number' => '5101016789012345',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Ani Yudhoyono',
                'email' => 'ani.yudhoyono@email.com',
                'nik' => '7301017890123456',
                'phone' => '081234567895',
                'gender' => 'female',
                'birth_date' => '1991-02-14',
                'address' => 'Jl. AP Pettarani No. 89',
                'city' => 'Makassar',
                'province' => 'Sulawesi Selatan',
                'postal_code' => '90222',
                'identity_type' => 'ktp',
                'identity_number' => '7301017890123456',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Joko Widodo',
                'email' => 'joko.widodo@email.com',
                'nik' => '1201018901234567',
                'phone' => '081234567896',
                'gender' => 'male',
                'birth_date' => '1980-09-30',
                'address' => 'Jl. Gajah Mada No. 34',
                'city' => 'Medan',
                'province' => 'Sumatera Utara',
                'postal_code' => '20112',
                'identity_type' => 'ktp',
                'identity_number' => '1201018901234567',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Megawati Sukarno',
                'email' => 'megawati.sukarno@email.com',
                'nik' => '3401019012345678',
                'phone' => '081234567897',
                'gender' => 'female',
                'birth_date' => '1993-04-18',
                'address' => 'Jl. Malioboro No. 67',
                'city' => 'Yogyakarta',
                'province' => 'DI Yogyakarta',
                'postal_code' => '55271',
                'identity_type' => 'ktp',
                'identity_number' => '3401019012345678',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Prabowo Subianto',
                'email' => 'prabowo.subianto@email.com',
                'nik' => '1301020123456789',
                'phone' => '081234567898',
                'gender' => 'male',
                'birth_date' => '1987-12-05',
                'address' => 'Jl. Khatib Sulaiman No. 23',
                'city' => 'Padang',
                'province' => 'Sumatera Barat',
                'postal_code' => '25122',
                'identity_type' => 'ktp',
                'identity_number' => '1301020123456789',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Sri Mulyani',
                'email' => 'sri.mulyani@email.com',
                'nik' => '3501021234567890',
                'phone' => '081234567899',
                'gender' => 'female',
                'birth_date' => '1994-06-22',
                'address' => 'Jl. Genteng No. 90',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60175',
                'identity_type' => 'ktp',
                'identity_number' => '3501021234567890',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Basuki Tjahaja',
                'email' => 'basuki.tjahaja@email.com',
                'nik' => '6101022345678901',
                'phone' => '081234567900',
                'gender' => 'male',
                'birth_date' => '1982-10-12',
                'address' => 'Jl. Sudirman No. 45',
                'city' => 'Pontianak',
                'province' => 'Kalimantan Barat',
                'postal_code' => '78121',
                'identity_type' => 'ktp',
                'identity_number' => '6101022345678901',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Rizal Ramli',
                'email' => 'rizal.ramli@email.com',
                'nik' => '1301023456789012',
                'phone' => '081234567901',
                'gender' => 'male',
                'birth_date' => '1989-01-28',
                'address' => 'Jl. Sam Ratulangi No. 78',
                'city' => 'Manado',
                'province' => 'Sulawesi Utara',
                'postal_code' => '95115',
                'identity_type' => 'ktp',
                'identity_number' => '1301023456789012',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Luhut Panjaitan',
                'email' => 'luhut.panjaitan@email.com',
                'nik' => '1201024567890123',
                'phone' => '081234567902',
                'gender' => 'male',
                'birth_date' => '1983-08-15',
                'address' => 'Jl. SM Raja No. 12',
                'city' => 'Medan',
                'province' => 'Sumatera Utara',
                'postal_code' => '20131',
                'identity_type' => 'ktp',
                'identity_number' => '1201024567890123',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Retno Marsudi',
                'email' => 'retno.marsudi@email.com',
                'nik' => '3301025678901234',
                'phone' => '081234567903',
                'gender' => 'female',
                'birth_date' => '1996-03-08',
                'address' => 'Jl. Pandanaran No. 56',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'postal_code' => '50241',
                'identity_type' => 'ktp',
                'identity_number' => '3301025678901234',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Erick Thohir',
                'email' => 'erick.thohir@email.com',
                'nik' => '3201026789012345',
                'phone' => '081234567904',
                'gender' => 'male',
                'birth_date' => '1986-11-20',
                'address' => 'Jl. Thamrin No. 89',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '10340',
                'identity_type' => 'ktp',
                'identity_number' => '3201026789012345',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Nadiem Makarim',
                'email' => 'nadiem.makarim@email.com',
                'nik' => '3201027890123456',
                'phone' => '081234567905',
                'gender' => 'male',
                'birth_date' => '1992-05-04',
                'address' => 'Jl. Rasuna Said No. 23',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '12950',
                'identity_type' => 'passport',
                'identity_number' => 'A12345678',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Sandiaga Uno',
                'email' => 'sandiaga.uno@email.com',
                'nik' => '3201028901234567',
                'phone' => '081234567906',
                'gender' => 'male',
                'birth_date' => '1984-07-17',
                'address' => 'Jl. Kuningan No. 67',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '12940',
                'identity_type' => 'ktp',
                'identity_number' => '3201028901234567',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Ganjar Pranowo',
                'email' => 'ganjar.pranowo@email.com',
                'nik' => '3301029012345678',
                'phone' => '081234567907',
                'gender' => 'male',
                'birth_date' => '1981-10-28',
                'address' => 'Jl. Pahlawan No. 34',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'postal_code' => '50241',
                'identity_type' => 'ktp',
                'identity_number' => '3301029012345678',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Anies Baswedan',
                'email' => 'anies.baswedan@email.com',
                'nik' => '3201030123456789',
                'phone' => '081234567908',
                'gender' => 'male',
                'birth_date' => '1988-02-07',
                'address' => 'Jl. Wijaya Kusuma No. 90',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '11630',
                'identity_type' => 'passport',
                'identity_number' => 'B87654321',
                'nationality' => 'Indonesia',
            ],
            [
                'name' => 'Ridwan Kamil',
                'email' => 'ridwan.kamil@email.com',
                'nik' => '3201031234567890',
                'phone' => '081234567909',
                'gender' => 'male',
                'birth_date' => '1990-10-04',
                'address' => 'Jl. Dago No. 123',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40135',
                'identity_type' => 'ktp',
                'identity_number' => '3201031234567890',
                'nationality' => 'Indonesia',
            ],
        ];

        foreach ($customers as $customer) {
            User::updateOrCreate(
                ['email' => $customer['email']],
                [
                    'name' => $customer['name'],
                    'password' => Hash::make('password123'),
                    'role' => 'customer',
                    'email_verified_at' => now(),
                    // Profile fields
                    'nik' => $customer['nik'],
                    'phone' => $customer['phone'],
                    'gender' => $customer['gender'],
                    'birth_date' => $customer['birth_date'],
                    'address' => $customer['address'],
                    'city' => $customer['city'],
                    'province' => $customer['province'],
                    'postal_code' => $customer['postal_code'],
                    'identity_type' => $customer['identity_type'],
                    'identity_number' => $customer['identity_number'],
                    'nationality' => $customer['nationality'],
                ]
            );
        }
        
        $this->command->info('✅ Berhasil membuat ' . count($customers) . ' customer dengan profil lengkap!');
    }
}